#!/bin/bash

# docker run --volume "$(pwd):/workspace" --workdir /workspace bufbuild/buf generate

protoc -I . --grpc-gateway_out ./gen/go \
    --grpc-gateway_opt paths=source_relative \
    --grpc-gateway_opt grpc_api_configuration=buf.gen.yaml \
    --grpc-gateway_opt standalone=true \
    api/api.proto
