name: Merge

on:
  push:
    branches:
      - main

jobs:
  vet:
    uses: ./.github/workflows/vet.yml
  unit-test:
    uses: ./.github/workflows/unit.yml
  build:
    needs: [vet, unit-test]
    uses: ./.github/workflows/build.yml
  push-to-ghcr:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} # if all `needs` jobs are successful
    needs: [vet, unit-test, build]
    secrets: inherit
    uses: ./.github/workflows/push-to-ghcr.yml
  cleanup:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} # if all `needs` jobs are successful
    needs: [push-to-ghcr]
    secrets: inherit
    uses: ./.github/workflows/cleanup.yml
